# 🔥 Aquecimento Hands-On: O seu Primeiro Transformer Customizado

**Objetivo:** Colocar a mão na massa desenvolvendo a sua própria de "peça de Lego" (Orientação a Objetos) para o Scikit-Learn antes de irmos para o laboratório principal.

---

## 🛠️ Cenário: O Conversor de Temperatura

Você tem uma base de dados simulando medições de sensores industriais em **Fahrenheit**. Sua missão é criar a classe `ConversorTemperatura` que receba essa base, aplique a fórmula aritmética para criar a conversão em **Celsius** e descarte a coluna antiga.

Fórmula: `C = (F - 32) * 5/9`

In [1]:
import pandas as pd

# Dados simulados para o nosso teste
df_sensores = pd.DataFrame({
    'ID_Sensor': [101, 102, 103],
    'Temp_Fahrenheit': [212.0, 32.0, 98.6]
})

display(df_sensores)

   ID_Sensor  Temp_Fahrenheit
0        101            212.0
1        102             32.0
2        103             98.6

---

## 🧑‍💻 Sua Tarefa: Construir a Classe
Preencha as lacunas (`_________`) e resolva a lógica de negócio no bloco de código abaixo para garantir que o seu transformador seja totalmente compatível com a API do Scikit-Learn.

In [2]:
from sklearn.base import BaseEstimator, TransformerMixin

# 1. HERANÇA: herdamos BaseEstimator e TransformerMixin para a classe funcionar com Pipeline
class ConversorTemperatura(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        pass
        
    def fit(self, X, y=None):
        # 2. RETORNO DO FIT: sem treinamento real, retornamos o próprio objeto
        return self
        
    def transform(self, X):
        # boa prática: copiar o DataFrame para não alterar o original
        X_modificado = X.copy()
        
        # 3. REGRA DE NEGÓCIO: converter Fahrenheit para Celsius
        X_modificado['Temp_Celsius'] = (X_modificado['Temp_Fahrenheit'] - 32) * 5.0 / 9.0
        
        # 4. LIMPEZA: remover a coluna antiga em Fahrenheit
        X_modificado = X_modificado.drop('Temp_Fahrenheit', axis=1)
        
        return X_modificado

print("Sintaxe validada com sucesso!")

Sintaxe validada com sucesso!

---

## 🧪 Testando a sua Peça de Lego
Execute a célula abaixo para ver o seu transformador em ação! O método `.fit_transform()` invoca sequencialmente o `fit` e depois o `transform` para você.

In [3]:
# Instanciando (Conectando o botão de ligar) o Conversor
meu_conversor = ConversorTemperatura()

# Aplicando o conversor nos dados
df_resultado = meu_conversor.fit_transform(df_sensores)

display(df_resultado)

   ID_Sensor  Temp_Celsius
0        101         100.0
1        102           0.0
2        103          37.0