# Lab 03 - Análise Exploratória de Dados (EDA): Variáveis Numéricas e Categóricas
**Disciplina:** Extração e Preparação de Dados | **Professor:** Luis Aramis

Neste laboratório, vamos aprender a diferenciar e tratar variáveis numéricas e categóricas usando a biblioteca Pandas. Utilizaremos o famoso dataset do **Titanic**.

## 1. Setup
Importe as bibliotecas necessárias.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns # Apenas para carregar o dataset, se necessário

## 2. Carregamento dos Dados
Vamos carregar o dataset do Titanic. O Pandas consegue ler diretamente de uma URL.

In [3]:
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)
print('Dataset carregado com sucesso!')

Dataset carregado com sucesso!

## 3. Inspeção Inicial
Use `.head()`, `.info()` para entender a estrutura dos dados.

In [16]:
# Visualizando as primeiras linhas
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
# Verificando tipos e nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 4. Análise de Variáveis Numéricas
Identifique as colunas numéricas (Age, Fare, etc.).
Use `.describe()` para ver estatísticas descritivas.

In [18]:
# Estatísticas descritivas das numéricas
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Exercício 4.1
Qual é a média de idade (`Age`) dos passageiros? E a mediana?

In [19]:
media_idade = df["Age"].mean()
mediana_idade = df["Age"].median()

print("Média:", media_idade)
print("Mediana:", mediana_idade)

Média: 29.69911764705882
Mediana: 28.0

## 5. Análise de Variáveis Categóricas
Identifique as colunas categóricas (Sex, Embarked, Pclass).
Use `.value_counts()` para ver a frequência de cada categoria.

In [20]:
# Contagem de passageiros por sexo
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [21]:
# Contagem de passageiros por classe (Pclass) - note que Pclass é numérico mas age como categoria ordinal
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## 6. Conversão de Tipos (Otimização)
Colunas como `Sex` e `Embarked` são lidas como `object` (string). Podemos converter para `category` para economizar memória e melhorar a semântica.

In [22]:
# Verificando memória antes
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 285.6 KB

In [23]:
# Convertendo
df["Sex"] = df["Sex"].astype("category")
df["Embarked"] = df["Embarked"].astype("category")

# Verificando memória depois
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    category
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    category
dtypes: category(2), float64(2), int64(5), object(3)
memory usage: 197.6 KB

## 7. Análise Multivariada Simples (GroupBy)
Vamos cruzar variáveis numéricas e categóricas.
Qual a tarifa média (`Fare`) paga por cada classe (`Pclass`)?

In [24]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

### Exercício 7.1
Qual a taxa de sobrevivência (`Survived` média) por sexo (`Sex`)?

In [25]:
# Seu código aqui
# Dica: Survived é 0 ou 1. A média de uma coluna binária é a proporção de 1s.
df.groupby("Sex")["Survived"].mean()

C:\Users\Milton\AppData\Local\Temp\ipykernel_35772\1709318149.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

---
## 8. DESAFIO PARA CASA
Utilize o mesmo dataset do Titanic para responder:
1. Quantos nomes únicos existem (`Name`)? Há nomes repetidos?
2. Crie uma nova coluna `FaixaEtaria` usando `pd.cut` na coluna `Age`.
   - 0-12: Criança
   - 12-18: Adolescente
   - 18-60: Adulto
   - 60+: Idoso
3. Conte quantos passageiros há em cada faixa etária.
4. (Opcional) Qual faixa etária teve maior taxa de sobrevivência?

In [26]:
# Seu código para o desafio aqui
print("Nomes únicos:", df["Name"].nunique())
print("Total de nomes:", df["Name"].count())
print("Há nomes repetidos?", df["Name"].nunique() != df["Name"].count())

df["FaixaEtaria"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 60, 120],
    labels=["Criança", "Adolescente", "Adulto", "Idoso"]
)

print(df["FaixaEtaria"].value_counts())

print(df.groupby("FaixaEtaria")["Survived"].mean())

Nomes únicos: 891
Total de nomes: 891
Há nomes repetidos? False
FaixaEtaria
Adulto         553
Adolescente     70
Criança         69
Idoso           22
Name: count, dtype: int64
FaixaEtaria
Criança        0.579710
Adolescente    0.428571
Adulto         0.388788
Idoso          0.227273
Name: Survived, dtype: float64

C:\Users\Milton\AppData\Local\Temp\ipykernel_35772\2328684662.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby("FaixaEtaria")["Survived"].mean())

---
## 9. DESAFIO EXTRA: Integração SQL + Pandas
Para consolidar o conhecimento da Aula 03, vamos fazer uma análise misturando SQL e Pandas.

**Cenário:** Você é um analista de dados na Chinook Music Store. A gerência quer entender o perfil de vendas por **Gênero Musical**.

**Atividade:**
1.  **Conexão:** Conecte-se ao banco `chinook.db` (o mesmo da aula passada).
2.  **Extração (SQL):** Escreva uma query que retorne uma tabela contendo: o **Nome do Gênero** (`Genres.Name`), o **Nome da Faixa** (`Tracks.Name`) e o **Preço Unitário** (`Tracks.UnitPrice`).
    -   *Dica:* Você precisará fazer um `JOIN` entre a tabela `Tracks` e a tabela `Genres`.
3.  **Carga:** Carregue esse resultado num DataFrame chamado `df_musicas`.
4.  **Análise (Pandas):**
    -   Qual é a média de preço das músicas de 'Rock' comparada com 'Latin'? (Análise Numérica por Categoria)
    -   Quantas músicas existem em cada gênero no catálogo? (Análise Categórica)
    -   Converta a coluna `Genre` para o tipo `category` e verifique a economia de memória.

In [27]:
# 1. Conexão com o Banco
import pandas as pd
from sqlalchemy import create_engine
import os
import urllib.request

if not os.path.exists("chinook.db"):
    url = "https://github.com/lerocha/chinook-database/raw/master/ChinookDatabase/DataSources/Chinook_Sqlite.sqlite"
    urllib.request.urlretrieve(url, "chinook.db")

engine = create_engine("sqlite:///chinook.db")

In [28]:
# 2. Query e Carga para DataFrame
query = """
SELECT Genre.Name AS Genre, Track.Name AS TrackName, Track.UnitPrice
FROM Track
JOIN Genre
    ON Track.GenreId = Genre.GenreId;
"""

df_musicas = pd.read_sql(query, engine)
df_musicas.head()

  Genre                                TrackName  UnitPrice
0  Rock  For Those About To Rock (We Salute You)       0.99
1  Rock                        Balls to the Wall       0.99
2  Rock                          Fast As a Shark       0.99
3  Rock                        Restless and Wild       0.99
4  Rock                     Princess of the Dawn       0.99

In [29]:
# 3. Análise dos Dados
print(df_musicas[df_musicas["Genre"].isin(["Rock", "Latin"])].groupby("Genre")["UnitPrice"].mean())

print(df_musicas["Genre"].value_counts())

df_musicas.info(memory_usage="deep")
df_musicas["Genre"] = df_musicas["Genre"].astype("category")
df_musicas.info(memory_usage="deep")

Genre
Latin    0.99
Rock     0.99
Name: UnitPrice, dtype: float64
Genre
Rock                  1297
Latin                  579
Metal                  374
Alternative & Punk     332
Jazz                   130
TV Shows                93
Blues                   81
Classical               74
Drama                   64
R&B/Soul                61
Reggae                  58
Pop                     48
Soundtrack              43
Alternative             40
Hip Hop/Rap             35
Electronica/Dance       30
World                   28
Heavy Metal             28
Sci Fi & Fantasy        26
Easy Listening          24
Comedy                  17
Bossa Nova              15
Science Fiction         13
Rock And Roll           12
Opera                    1
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3503 entries, 0 to 3502
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Genre      3503 non-null   object
 1   TrackName  3503 non-null   object
 2   UnitPrice  3503 non-null   float64
dtypes: float64(1), object(2)
memory usage: 444.0 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3503 entries, 0 to 3502
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Genre      3503 non-null   category
 1   TrackName  3503 non-null   object
 2   UnitPrice  3503 non-null   float64
dtypes: category(1), float64(1), object(1)
memory usage: 259.1 KB